name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make
    
    - name: Build taskman
      run: make
    
    - name: Test basic functionality
      run: |
        ./taskman help
        ./taskman add "Test task 1"
        ./taskman add "Test task 2"
        ./taskman list
        ./taskman done 1
        ./taskman list-all
        ./taskman delete 2
        ./taskman list
    
    - name: Clean build
      run: make clean
